# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2022-07-15 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_auto_20160306_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='campionato',
            field=models.BooleanField(default=True, verbose_name='Partita di campionato'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='gare',
            field=models.IntegerField(verbose_name='Numero di gare disputate'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='punteggio11',
            field=models.IntegerField(default=0, verbose_name='Prima squadra, primo giocatore'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='punteggio12',
            field=models.IntegerField(default=0, verbose_name='Prima squadra, secondo giocatore'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='punteggio21',
            field=models.IntegerField(default=0, verbose_name='Seconda squadra, primo giocatore'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='punteggio22',
            field=models.IntegerField(default=0, verbose_name='Seconda squadra, secondo giocatore'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='squadra1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite1', to='torneo.Squadra', verbose_name='Prima squadra'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='squadra2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partite2', to='torneo.Squadra', verbose_name='Seconda squadra'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='stato',
            field=models.CharField(choices=[('INC', 'Partita non disputata'), ('AT1', 'In attesa di conferma dalla prima squadra'), ('AT2', 'In attesa di conferma della seconda squadra'), ('DON', 'Punteggio confermato')], default='INC', max_length=3),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='giocatore1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre1', to=settings.AUTH_USER_MODEL, verbose_name='Primo giocatore'),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='giocatore2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre2', to=settings.AUTH_USER_MODEL, verbose_name='Secondo giocatore'),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='immagine',
            field=models.ImageField(default='torneo/squadra/default.png', upload_to='torneo/squadra'),
        ),
        migrations.AlterField(
            model_name='squadra',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome della squadra'),
        ),
    ]
